<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <RootNamespace>Forza_Horizon_6_Tune_Master</RootNamespace>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>icon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Text.Json" Version="8.0.5" />
    </ItemGroup>

    <ItemGroup>
        <Resource Include="icon.ico"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Localization\*.json"/>
    </ItemGroup>

</Project>
