using Forza_Horizon_6_Tune_Master.Models;

namespace TuneMaster.Tests.Helpers;

public static class CarFactory
{
    public static CarCard DefaultCar() => new()
    {
        Name = "Test Car",
        Make = "TestMake",
        Model = "TestModel",
        Year = 2024,
        TotalMass = 1400,
        WeightDistributionFront = 50,
        PowerHP = 300,
        TorqueNm = 400,
        MaxRPM = 7000,
        EngineType = EngineType.V6,
        EnginePosition = EnginePosition.Front,
        AspirationType = AspirationType.Natural,
        FuelType = FuelType.Gasoline,
        PowertrainType = PowertrainType.ICE,
        DriveType = DriveType.RWD,
        GearCount = 6,
        AllowGearCalculation = true,
        FrontTireWidth = 235,
        FrontTireProfile = 40,
        RearTireWidth = 265,
        RearTireProfile = 35,
        FrontRimDiameter = 19,
        RearRimDiameter = 19,
        TireType = TireType.Sport,
        Wheelbase = 2700,
        FrontTrack = 1550,
        RearTrack = 1570,
        Cd = 0,
        FrontalAreaM2 = 0,
        HasFrontAero = true,
        HasRearAero = true,
        SuspensionUpgrade = SuspensionUpgrade.Race,
        DifferentialUpgrade = DifferentialUpgrade.Race,
        BrakesUpgrade = BrakesUpgrade.Race,
    };

    public static CarCard FWDStockCar() => new()
    {
        Name = "FWD Stock",
        Make = "Honda",
        Model = "Civic",
        Year = 2020,
        TotalMass = 1200,
        WeightDistributionFront = 60,
        PowerHP = 180,
        TorqueNm = 200,
        MaxRPM = 6800,
        EngineType = EngineType.I4,
        EnginePosition = EnginePosition.Front,
        AspirationType = AspirationType.Natural,
        PowertrainType = PowertrainType.ICE,
        DriveType = DriveType.FWD,
        GearCount = 6,
        FrontTireWidth = 205,
        FrontTireProfile = 50,
        RearTireWidth = 205,
        RearTireProfile = 50,
        FrontRimDiameter = 16,
        RearRimDiameter = 16,
        TireType = TireType.Stock,
        SuspensionUpgrade = SuspensionUpgrade.Stock,
        DifferentialUpgrade = DifferentialUpgrade.Stock,
        HasFrontAero = false,
        HasRearAero = false,
    };

    public static CarCard AWDPerformanceCar() => new()
    {
        Name = "AWD Performance",
        Make = "Nissan",
        Model = "GT-R",
        Year = 2022,
        TotalMass = 1740,
        WeightDistributionFront = 55,
        PowerHP = 565,
        TorqueNm = 633,
        MaxRPM = 7000,
        EngineType = EngineType.V6,
        EnginePosition = EnginePosition.Front,
        AspirationType = AspirationType.TwinTurbo,
        AntiLag = true,
        PowertrainType = PowertrainType.ICE,
        DriveType = DriveType.AWD,
        GearCount = 6,
        FrontTireWidth = 255,
        FrontTireProfile = 40,
        RearTireWidth = 285,
        RearTireProfile = 35,
        FrontRimDiameter = 20,
        RearRimDiameter = 20,
        TireType = TireType.SemiSlick,
        Wheelbase = 2780,
        FrontTrack = 1590,
        RearTrack = 1600,
        Cd = 0.32,
        FrontalAreaM2 = 2.15,
        HasFrontAero = true,
        HasRearAero = true,
        SuspensionUpgrade = SuspensionUpgrade.Race,
        DifferentialUpgrade = DifferentialUpgrade.Race,
        BrakesUpgrade = BrakesUpgrade.Race,
    };

    public static CarCard ElectricCar() => new()
    {
        Name = "Electric",
        Make = "Tesla",
        Model = "Model S Plaid",
        Year = 2023,
        TotalMass = 2100,
        WeightDistributionFront = 48,
        PowerHP = 1020,
        TorqueNm = 1400,
        MaxRPM = 20000,
        EngineType = EngineType.I4,
        EnginePosition = EnginePosition.Rear,
        AspirationType = null,
        PowertrainType = PowertrainType.Electric,
        DriveType = DriveType.AWD,
        GearCount = 1,
        FrontTireWidth = 255,
        FrontTireProfile = 35,
        RearTireWidth = 275,
        RearTireProfile = 35,
        FrontRimDiameter = 21,
        RearRimDiameter = 21,
        TireType = TireType.Sport,
        HasFrontAero = false,
        HasRearAero = false,
        SuspensionUpgrade = SuspensionUpgrade.Sport,
        DifferentialUpgrade = DifferentialUpgrade.Sport,
    };

    public static TrackInfo DefaultTrack() => new()
    {
        Discipline = Discipline.Road,
        DragDistance = DragDistance.Quarter,
    };

    public static TuningConstraints DefaultConstraints() => new();

    public static TuningConstraints RelaxedConstraints() => new()
    {
        TirePressureFrontMin = 0.5, TirePressureFrontMax = 5.0,
        TirePressureRearMin = 0.5, TirePressureRearMax = 5.0,
        CamberFrontMin = -10, CamberFrontMax = 10,
        CamberRearMin = -10, CamberRearMax = 10,
        ToeFrontMin = -10, ToeFrontMax = 10,
        ToeRearMin = -10, ToeRearMax = 10,
        CasterMin = 0, CasterMax = 15,
        ARBFrontMin = 0, ARBFrontMax = 100,
        ARBRearMin = 0, ARBRearMax = 100,
        SpringFrontMin = 10, SpringFrontMax = 600,
        SpringRearMin = 10, SpringRearMax = 600,
        RideHeightFrontMin = 10, RideHeightFrontMax = 400,
        RideHeightRearMin = 10, RideHeightRearMax = 400,
        ReboundFrontMin = 0, ReboundFrontMax = 30,
        ReboundRearMin = 0, ReboundRearMax = 30,
        BumpFrontMin = 0, BumpFrontMax = 30,
        BumpRearMin = 0, BumpRearMax = 30,
        AeroFrontMin = 0, AeroFrontMax = 200,
        AeroRearMin = 0, AeroRearMax = 200,
        DiffAccelMin = 0, DiffAccelMax = 100,
        DiffDecelMin = 0, DiffDecelMax = 100,
        BrakeBalanceMin = 20, BrakeBalanceMax = 80,
        BrakePressureMin = 20, BrakePressureMax = 300,
        FinalDriveMin = 0.5, FinalDriveMax = 12,
        CenterDiffBias = 50,
    };
}
